<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;
use App\Models\Places; // your Places model

class ActivitiesTableSeeder extends Seeder
{
    public function run(): void
    {
        $allPlaces = Places::all();

        if ($allPlaces->isEmpty()) 
        {
            $this->command->info('No places found. Please seed Places first.');
            return;
        }

        // Example dummy  (50+)
       $Data = [
    [
        'place_id' => 1,
        'name' => 'Ride a Horse',
        'description' => 'Experience the thrill of riding a horse with expert instructors guiding a group of five. This 40-minute session covers basic riding skills and trail riding through scenic paths.',
        'location' => 'Sunny Meadows Ranch, Pine Trail, Springfield',
        'imagen' => 'horse_riding.jfif',
        'price' => 50,
        'date' => '2026-03-01',
        'is_active' => true,
    ],
    [
        'place_id' => 2,
        'name' => 'Hiking Adventure',
        'description' => 'Join a guided mountain hike exploring nature trails, diverse flora and fauna, and stunning views. Suitable for intermediate hikers looking for adventure and exercise.',
        'location' => 'Rocky Ridge Park, Mountain Road, Springfield',
        'imagen' => 'hiking.jfif',
        'price' => 60,
        'date' => '2026-03-02',
        'is_active' => true,
    ],
    [
        'place_id' => 3,
        'name' => 'City Walking Tour',
        'description' => 'Explore hidden gems and historical landmarks of the city on foot with a knowledgeable guide. Ideal for culture enthusiasts and casual explorers.',
        'location' => 'Downtown, Main Street, Springfield',
        'imagen' => 'city_tour.jfif',
        'price' => 25,
        'date' => '2026-03-03',
        'is_active' => true,
    ],
    [
        'place_id' => 4,
        'name' => 'Kayaking',
        'description' => 'Enjoy two hours of kayaking on calm lakes and rivers, perfect for all skill levels. Safety equipment and expert guidance provided throughout.',
        'location' => 'Lakeview Dock, Lake Street, Springfield',
        'imagen' => 'kayaking.jfif',
        'price' => 40,
        'date' => '2026-03-04',
        'is_active' => true,
    ],
    [
        'place_id' => 5,
        'name' => 'Cycling Tour',
        'description' => 'Take a guided cycling tour around scenic city routes and parks. Suitable for casual and experienced cyclists wanting to discover the area.',
        'location' => 'Riverside Park, Elm Avenue, Springfield',
        'imagen' => 'cycling.jfif',
        'price' => 35,
        'date' => '2026-03-05',
        'is_active' => true,
    ],
    [
        'place_id' => 6,
        'name' => 'Boat Cruise',
        'description' => 'Relax on a peaceful boat cruise along the river, enjoying beautiful views and fresh air. Ideal for families and couples looking to unwind.',
        'location' => 'Harbor Pier, Waterfront Road, Springfield',
        'imagen' => 'boat_cruise.jfif',
        'price' => 45,
        'date' => '2026-03-06',
        'is_active' => true,
    ],
    [
        'place_id' => 7,
        'name' => 'Wine Tasting',
        'description' => 'Sample exquisite local wines in a guided tasting session that explores flavor profiles, vineyard history, and pairing suggestions.',
        'location' => 'Vineyard Estate, Grape Lane, Springfield',
        'imagen' => 'wine_tasting.jfif',
        'price' => 55,
        'date' => '2026-03-07',
        'is_active' => true,
    ],
    [
        'place_id' => 8,
        'name' => 'Cooking Class',
        'description' => 'Learn to cook traditional dishes under the guidance of local chefs. This interactive session includes hands-on preparation and tasting.',
        'location' => 'Gourmet Kitchen Studio, Oak Street, Springfield',
        'imagen' => 'cooking_class.jfif',
        'price' => 50,
        'date' => '2026-03-08',
        'is_active' => true,
    ],
    [
        'place_id' => 9,
        'name' => 'Snorkeling',
        'description' => 'Discover vibrant underwater life with a guided snorkeling adventure in crystal-clear waters, suitable for all experience levels.',
        'location' => 'Coral Bay, Seaside Road, Springfield',
        'imagen' => 'snorkeling.jfif',
        'price' => 65,
        'date' => '2026-03-09',
        'is_active' => true,
    ],
    [
        'place_id' => 10,
        'name' => 'Scuba Diving',
        'description' => 'Beginner-friendly scuba diving with professional instructors. Explore underwater reefs and marine biodiversity in a safe environment.',
        'location' => 'Ocean Dive Center, Marina Blvd, Springfield',
        'imagen' => 'scuba_diving.jfif',
        'price' => 80,
        'date' => '2026-03-10',
        'is_active' => true,
    ],
    [
        'place_id' => 11,
        'name' => 'Rock Climbing',
        'description' => 'Scale natural rock formations with expert guidance. Suitable for all skill levels, focusing on technique, safety, and enjoyment.',
        'location' => 'Cliffside Park, Rock Lane, Springfield',
        'imagen' => 'rock_climbing.jfif',
        'price' => 70,
        'date' => '2026-03-11',
        'is_active' => true,
    ],
    [
        'place_id' => 12,
        'name' => 'Paragliding',
        'description' => 'Experience the thrill of flying over mountains and valleys with professional instructors. Safety briefing and equipment included.',
        'location' => 'Eagle Peak, Summit Road, Springfield',
        'imagen' => 'paragliding.jfif',
        'price' => 120,
        'date' => '2026-03-12',
        'is_active' => true,
    ],
    [
        'place_id' => 13,
        'name' => 'Skiing',
        'description' => 'Enjoy ski slopes with professional guidance suitable for beginners and advanced skiers. Equipment rental available on site.',
        'location' => 'Snowy Hills Ski Resort, Alpine Road, Springfield',
        'imagen' => 'skiing.jfif',
        'price' => 90,
        'date' => '2026-03-13',
        'is_active' => true,
    ],
    [
        'place_id' => 14,
        'name' => 'Snowboarding',
        'description' => 'Join a snowboarding session for all levels, focusing on techniques, balance, and safety on fresh snowy slopes.',
        'location' => 'Snowy Hills Ski Resort, Alpine Road, Springfield',
        'imagen' => 'snowboarding.jfif',
        'price' => 85,
        'date' => '2026-03-14',
        'is_active' => true,
    ],
    [
        'place_id' => 15,
        'name' => 'Zip Lining',
        'description' => 'Fly through the treetops on an exhilarating zip line course, guided by trained instructors with all safety gear provided.',
        'location' => 'Adventure Park, Forest Drive, Springfield',
        'imagen' => 'zip_lining.jfif',
        'price' => 45,
        'date' => '2026-03-15',
        'is_active' => true,
    ],
    [
        'place_id' => 16,
        'name' => 'Cultural Tour',
        'description' => 'Explore historic landmarks and cultural sites with an expert guide, learning about the local heritage and traditions.',
        'location' => 'Old Town, Heritage Street, Springfield',
        'imagen' => 'cultural_tour.jfif',
        'price' => 30,
        'date' => '2026-03-16',
        'is_active' => true,
    ],
    [
        'place_id' => 17,
        'name' => 'Photography Tour',
        'description' => 'Capture beautiful cityscapes and nature shots on a guided photography tour with tips from professional photographers.',
        'location' => 'Panorama Hill, Camera Street, Springfield',
        'imagen' => 'photography_tour.jfif',
        'price' => 35,
        'date' => '2026-03-17',
        'is_active' => true,
    ],
    [
        'place_id' => 18,
        'name' => 'Bird Watching',
        'description' => 'Join a guided tour in nature reserves to observe and learn about local bird species with binoculars and expert insights.',
        'location' => 'Greenwood Reserve, Forest Lane, Springfield',
        'imagen' => 'bird_watching.jfif',
        'price' => 25,
        'date' => '2026-03-18',
        'is_active' => true,
    ],
    [
        'place_id' => 19,
        'name' => 'Fishing Trip',
        'description' => 'Spend a day fishing with experienced guides who provide all necessary equipment and share tips for catching local fish.',
        'location' => 'Silver Lake, Fisherman\'s Wharf, Springfield',
        'imagen' => 'fishing_trip.jfif',
        'price' => 40,
        'date' => '2026-03-19',
        'is_active' => true,
    ],
    [
        'place_id' => 20,
        'name' => 'Kayak Safari',
        'description' => 'Explore rivers and lakes on a guided kayak safari, observing wildlife and enjoying peaceful waterways.',
        'location' => 'Riverbend Park, Waterside Road, Springfield',
        'imagen' => 'kayaking.jfif',
        'price' => 50,
        'date' => '2026-03-20',
        'is_active' => true,
    ],
    [
        'place_id' => 21,
        'name' => 'Mountain Biking',
        'description' => 'Experience thrilling trails on mountain paths with guided support, suited for adventurous cyclists of varying skill levels.',
        'location' => 'Trailblazer Park, Mountain Road, Springfield',
        'imagen' => 'mountain_biking.jfif',
        'price' => 60,
        'date' => '2026-03-21',
        'is_active' => true,
    ],
    [
        'place_id' => 22,
        'name' => 'Hot Air Balloon Ride',
        'description' => 'Enjoy a breathtaking sunrise from above on a peaceful hot air balloon ride, complete with a pre-flight briefing and refreshments.',
        'location' => 'Skyview Launch Site, Hilltop Road, Springfield',
        'imagen' => 'hot_air_balloon.jfif',
        'price' => 150,
        'date' => '2026-03-22',
        'is_active' => true,
    ],
    [
        'place_id' => 23,
        'name' => 'Cave Exploration',
        'description' => 'Discover hidden caves and underground formations on a guided exploration, with safety equipment and expert instruction provided.',
        'location' => 'Echo Caverns, Rocky Road, Springfield',
        'imagen' => 'cave_exploration.jfif',
        'price' => 55,
        'date' => '2026-03-23',
        'is_active' => true,
    ],
    [
        'place_id' => 24,
        'name' => 'Horse Carriage Ride',
        'description' => 'Take a relaxing horse-drawn carriage ride through charming city streets, ideal for romantic outings and sightseeing.',
        'location' => 'Old Town Square, Market Street, Springfield',
        'imagen' => 'horse_carriage.jfif',
        'price' => 30,
        'date' => '2026-03-24',
        'is_active' => true,
    ],
    [
        'place_id' => 25,
        'name' => 'Museum Tour',
        'description' => 'Learn about history, art, and culture with a guided tour of local museums featuring curated exhibitions and interactive displays.',
        'location' => 'City Museum, History Lane, Springfield',
        'imagen' => 'museum.jfif',
        'price' => 20,
        'date' => '2026-03-25',
        'is_active' => true,
    ],
    [
        'place_id' => 26,
        'name' => 'Street Art Tour',
        'description' => 'Discover vibrant murals, graffiti, and street art across the city with a guide who explains the artists’ stories and techniques.',
        'location' => 'Art District, 5th Avenue, Springfield',
        'imagen' => 'street_art.jfif',
        'price' => 25,
        'date' => '2026-03-26',
        'is_active' => true,
    ],
    [
        'place_id' => 27,
        'name' => 'Yoga Class',
        'description' => 'Participate in outdoor yoga sessions in scenic parks designed to improve flexibility, balance, and mental focus for all skill levels.',
        'location' => 'Lakeside Park, Serenity Road, Springfield',
        'imagen' => 'yoga.jfif',
        'price' => 15,
        'date' => '2026-03-27',
        'is_active' => true,
    ],
    [
        'place_id' => 28,
        'name' => 'Meditation Session',
        'description' => 'Experience guided meditation in peaceful natural settings to promote relaxation, mindfulness, and stress relief.',
        'location' => 'Forest Grove, Tranquility Path, Springfield',
        'imagen' => 'meditation.jfif',
        'price' => 10,
        'date' => '2026-03-28',
        'is_active' => true,
    ],
    [
        'place_id' => 29,
        'name' => 'Local Market Tour',
        'description' => 'Explore local markets offering fresh food, handmade crafts, and cultural experiences with an expert guide.',
        'location' => 'Central Market, Main Street, Springfield',
        'imagen' => 'market_tour.jfif',
        'price' => 20,
        'date' => '2026-03-29',
        'is_active' => true,
    ],
    [
        'place_id' => 30,
        'name' => 'Historical Walking Tour',
        'description' => 'Discover the city’s rich history on foot, visiting important landmarks and hearing stories from knowledgeable guides.',
        'location' => 'Heritage District, Old Town Road, Springfield',
        'imagen' => 'historical_walk.jfif',
        'price' => 25,
        'date' => '2026-03-30',
        'is_active' => true,
    ],
    [
        'place_id' => 31,
        'name' => 'Sunset Cruise',
        'description' => 'Relax on an evening boat ride to watch the sunset over the river, complete with light refreshments and stunning views.',
        'location' => 'Harbor Pier, Waterfront Road, Springfield',
        'imagen' => 'boat_cruise.jfif',
        'price' => 50,
        'date' => '2026-03-31',
        'is_active' => true,
    ],
    [
        'place_id' => 32,
        'name' => 'Jet Ski Adventure',
        'description' => 'Feel the thrill of speeding across the water on a jet ski, with safety instructions and equipment provided.',
        'location' => 'Lakeside Marina, Dock Road, Springfield',
        'imagen' => 'jet_ski.jfif',
        'price' => 70,
        'date' => '2026-04-01',
        'is_active' => true,
    ],
    [
        'place_id' => 33,
        'name' => 'Surfing Lesson',
        'description' => 'Learn surfing basics with professional instructors on safe, beginner-friendly waves at the beach.',
        'location' => 'Seaside Beach, Ocean Avenue, Springfield',
        'imagen' => 'surfing.jfif',
        'price' => 60,
        'date' => '2026-04-02',
        'is_active' => true,
    ],
    [
        'place_id' => 34,
        'name' => 'Snorkeling Safari',
        'description' => 'Dive into crystal-clear waters with our guided snorkeling safari. Explore coral reefs, observe marine life, and enjoy a safe and immersive underwater experience suitable for all skill levels.',
        'location' => 'Coral Bay, Seaside Road, Springfield',
        'imagen' => 'snorkeling.jfif',
        'price' => 65,
        'date' => '2026-04-03',
        'is_active' => true,
    ],
    [
        'place_id' => 35,
        'name' => 'Trekking Challenge',
        'description' => 'Join a full-day mountain trekking adventure led by expert guides. Explore rugged trails, enjoy breathtaking vistas, and test your endurance in a challenging yet rewarding outdoor experience.',
        'location' => 'Rocky Trail Park, Mountain Road, Springfield',
        'imagen' => 'hiking.jfif',
        'price' => 75,
        'date' => '2026-04-04',
        'is_active' => true,
    ],
    [
        'place_id' => 36,
        'name' => 'Rocky Mountain Hike',
        'description' => 'Trek through challenging rocky terrain with guided assistance, discovering panoramic landscapes and unique geological features. This hike is ideal for adventure enthusiasts seeking an immersive outdoor experience.',
        'location' => 'Rocky Mountain Park, Summit Road, Springfield',
        'imagen' => 'hiking.jfif',
        'price' => 80,
        'date' => '2026-04-05',
        'is_active' => true,
    ],
    [
        'place_id' => 37,
        'name' => 'Desert Safari',
        'description' => 'Explore the desert landscape in 4x4 vehicles with professional guides. Experience sand dunes, unique wildlife, and traditional cultural stops for an unforgettable adventure under the sun.',
        'location' => 'Golden Dunes Desert, Sahara Road, Springfield',
        'imagen' => 'desert_safari.jfif',
        'price' => 90,
        'date' => '2026-04-06',
        'is_active' => true,
    ],
    [
        'place_id' => 38,
        'name' => 'Glacier Walk',
        'description' => 'Embark on a guided trek across stunning glaciers with expert equipment and safety measures. Learn about glacial formations and enjoy a once-in-a-lifetime icy adventure.',
        'location' => 'Glacier National Park, Ice Trail, Springfield',
        'imagen' => 'glacier_walk.jfif',
        'price' => 100,
        'date' => '2026-04-07',
        'is_active' => true,
    ],
    [
        'place_id' => 39,
        'name' => 'Island Hopping',
        'description' => 'Visit multiple tropical islands by boat, enjoying beautiful beaches, snorkeling spots, and local culture. Perfect for travelers seeking variety and relaxation.',
        'location' => 'Tropical Archipelago, Harbor Road, Springfield',
        'imagen' => 'boat_cruise.jfif',
        'price' => 120,
        'date' => '2026-04-08',
        'is_active' => true,
    ],
    [
        'place_id' => 40,
        'name' => 'Cultural Dance Class',
        'description' => 'Learn traditional dances from expert instructors in a fun and interactive class that celebrates local culture and rhythm.',
        'location' => 'Community Center, Dance Hall, Springfield',
        'imagen' => 'dance_class.jfif',
        'price' => 35,
        'date' => '2026-04-09',
        'is_active' => true,
    ],
    [
        'place_id' => 41,
        'name' => 'Pottery Workshop',
        'description' => 'Get creative with clay in a pottery workshop led by skilled artisans. Learn techniques for shaping, glazing, and firing your own unique pieces.',
        'location' => 'Artisan Studio, Craft Street, Springfield',
        'imagen' => 'pottery.jfif',
        'price' => 40,
        'date' => '2026-04-10',
        'is_active' => true,
    ],
    [
        'place_id' => 42,
        'name' => 'Photography Workshop',
        'description' => 'Improve your photography skills with hands-on lessons from professionals. Explore composition, lighting, and editing techniques in a supportive environment.',
        'location' => 'Creative Hub, Studio Road, Springfield',
        'imagen' => 'photography_tour.jfif',
        'price' => 50,
        'date' => '2026-04-11',
        'is_active' => true,
    ],
    [
        'place_id' => 43,
        'name' => 'Wildlife Safari',
        'description' => 'Observe diverse wildlife in their natural habitats on a guided safari tour. Learn about animal behavior and conservation efforts while enjoying an unforgettable outdoor experience.',
        'location' => 'Nature Reserve, Safari Drive, Springfield',
        'imagen' => 'wildlife_safari.jfif',
        'price' => 120,
        'date' => '2026-04-12',
        'is_active' => true,
    ],
    [
        'place_id' => 44,
        'name' => 'Cooking Experience',
        'description' => 'Cook alongside local chefs and learn authentic recipes in an immersive culinary experience. Enjoy tasting your creations and taking home new skills.',
        'location' => 'Gourmet Kitchen Studio, Oak Street, Springfield',
        'imagen' => 'cooking_class.jfif',
        'price' => 60,
        'date' => '2026-04-13',
        'is_active' => true,
    ],
    [
        'place_id' => 45,
        'name' => 'Chocolate Tasting',
        'description' => 'Sample a variety of exquisite chocolates in a tasting session that explores origins, flavor profiles, and pairing ideas.',
        'location' => 'Sweet Delights Shop, Candy Lane, Springfield',
        'imagen' => 'chocolate_tasting.jfif',
        'price' => 30,
        'date' => '2026-04-14',
        'is_active' => true,
    ],
    [
        'place_id' => 46,
        'name' => 'Cheese Tasting',
        'description' => 'Discover the best local cheeses with expert guidance, learning about production methods and tasting techniques.',
        'location' => 'Cheese Cellar, Dairy Road, Springfield',
        'imagen' => 'cheese_tasting.jfif',
        'price' => 30,
        'date' => '2026-04-15',
        'is_active' => true,
    ],
    [
        'place_id' => 47,
        'name' => 'Bike and Brew Tour',
        'description' => 'Cycle through scenic routes and enjoy local craft beers in this combined biking and tasting tour, perfect for active beer lovers.',
        'location' => 'Brewery District, Craft Lane, Springfield',
        'imagen' => 'cycling.jfif',
        'price' => 45,
        'date' => '2026-04-16',
        'is_active' => true,
    ],
    [
        'place_id' => 48,
        'name' => 'Fishing Safari',
        'description' => 'Enjoy a full-day guided fishing tour with expert advice, boat access, and equipment provided to maximize your catch.',
        'location' => 'Silver Lake, Fisherman\'s Wharf, Springfield',
        'imagen' => 'fishing_trip.jfif',
        'price' => 70,
        'date' => '2026-04-17',
        'is_active' => true,
    ],
    [
        'place_id' => 49,
        'name' => 'Horseback Safari',
        'description' => 'Ride through natural reserves on horseback, observing wildlife and beautiful landscapes with knowledgeable guides.',
        'location' => 'Nature Reserve, Trail Road, Springfield',
        'imagen' => 'horse_riding.jpg',
        'price' => 80,
        'date' => '2026-04-18',
        'is_active' => true,
    ],
    [
        'place_id' => 50,
        'name' => 'Sunrise Trek',
        'description' => 'Start your day with a morning trek to catch the sunrise from scenic viewpoints. Enjoy peaceful surroundings and fresh mountain air.',
        'location' => 'Sunrise Hill, Mountain Path, Springfield',
        'imagen' => 'hiking.jfif',
        'price' => 40,
        'date' => '2026-04-19',
        'is_active' => true,
    ],
];


       foreach ($Data as $activity) {
    $place = $allPlaces->random();

    // Remove any leading slashes from imagen
    $imagenFile = ltrim($activity['imagen'], '/');

    Activity::create(array_merge($activity, [
        'place_id' => $place->id,
        'location' => $place->city ?? 'Unknown',
        'imagen' => $imagenFile, // just the filename
        'lat' => $place->lat ?? null,
        'lng' => $place->lng ?? null,
        'distance' => rand(1, 20), // km
        'duration' => rand(30, 180) * 60, // seconds
        'avg_speed' => rand(5, 20), // km/h
        'elevation_gain' => rand(50, 500), // meters
        'track_points' => json_encode([
            ['lat' => $place->lat ?? 0, 'lng' => $place->lng ?? 0],
            ['lat' => ($place->lat ?? 0) + 0.01, 'lng' => ($place->lng ?? 0) + 0.01],
            ['lat' => ($place->lat ?? 0) + 0.02, 'lng' => ($place->lng ?? 0) + 0.02],
        ]),
        'completed_at' => now(),
    ]));

        }

        $this->command->info(' seeded successfully!');
    }
}
